# Generated by Django 5.1.5 on 2025-02-03 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_web", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagepair",
            name="id",
        ),
        migrations.AddField(
            model_name="messagepair",
            name="message_pair_id",
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False
            )
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "conversation_id"],
                name="conversatio_user_id_74deda_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagepair",
            index=models.Index(
                fields=["conversation", "message_pair_id"],
                name="MessagePair_convers_8f7934_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="conversation",
            table="conversations",
        ),
        migrations.AlterModelTable(
            name="messagepair",
            table="MessagePair",
        ),
    ]
