# Generated by Django 5.1.5 on 2025-02-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("others", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
